### ISSUE TITLE
How to load online http url json file (eg http://ip_address/en.json)

### ISSUE THREAD

**Issue by tj3333** [aissat/easy_localization#480] opened 2022-05-02 10:08 UTC

**Comment by moazelsawaf** [comment] 2022-07-31 00:40
Check out this part in the documentation [Loading translations from other resources](https://pub.dev/packages/easy_localization#-loading-translations-from-other-resources)

You will find a loader called `HttpAssetLoader`, it will do the job.

https://github.com/aissat/easy_localization_loader

**Comment by pranav-asthi** [comment] 2022-08-02 05:12
Passed HttpAssetLoader as assetLoader and path is set to url. But showing localization for key not found warning message

**Comment by bw-flagship** [comment] 2023-05-14 12:25
Closing it since the question is answered. If there are any further problems/questions, please open a new issue including code to reproduce

**Closed as completed by bw-flagship** 2023-05-14 12:25 UTC
