### ISSUE TITLE
setLocale(Locale) doesn't refresh the widgets.

### ISSUE THREAD

**Issue by omensight** [aissat/easy_localization#615] opened 2023-09-01 02:01 UTC
Hi, I am using Riverpod alongside EeasyLocalization:
This is a listener of a Riverpod provider that is in the Navigation view:

```
ref.listen(selectedLocalizationProvider, (previous, localization) {
      var languageCode = localization.locale.$1;
      var countryCode = localization.locale.$2;
      print('$languageCode-$countryCode');
      if (countryCode != null) {
        EasyLocalization.of(context)
            ?.setLocale(Locale(languageCode, countryCode));
      } else {
        EasyLocalization.of(context)?.setLocale(Locale(languageCode));
      }
    });
```

It effectively changes the locale to the respective language and country code like it shows in the debug console:
```
flutter: [🌎 Easy Localization] [INFO] Locale en_US changed
flutter: [🌎 Easy Localization] [INFO] Locale en_US saved
flutter: [🌎 Easy Localization] [DEBUG] Build
flutter: [🌎 Easy Localization] [DEBUG] Init Localization Delegate
flutter: [🌎 Easy Localization] [DEBUG] Init provider
```

The way I am using localizations is with the generator and translating them with:
```
LocaleKeys.installByDefault.tr()
```

And I have also tried passing the context object:

```
LocaleKeys.installByDefault.tr(context: context)
```

But nothing seems to work.

One more thing is I'm configuring EasyLocalizations in the next way:

```
runApp(ProviderScope(
    child: EasyLocalization(
        assetLoader: const CodegenLoader(),
        supportedLocales: const [
          Locale('en', 'US'),
          Locale('es'),
        ],
        fallbackLocale: const Locale('en', 'US'),
        path: 'assets/langs',
        child: const NoClickApp()),
  ));
```
Thank you so much.

**Comment by omensight** [comment] 2023-09-01 12:35
This is an example code:
https://github.com/omensight/easy_localization_bug_example

**Comment by omensight** [comment] 2023-09-04 16:41
Well, I haven't fixed it yet, but I got a workaround.
I have used the:
```
Process.run('current_executable.exe',[]);
```
and immediately called to 
```
exit(0);
```

It indeed changes the locale, but the cost is the continuity if you are still debugging.

**Comment by can-bigpay** [comment] 2023-09-05 08:10
have the same issue it refreshes on hot reload, I guess can fix it putting a provider and consumer on top but this package should already be handling this I believe
Edit: it doesn't get fixed with provider & consumer approach

**Comment by aissat** [comment] 2023-09-05 13:45
Duplicate of #590

**Closed as completed** 2023-09-12 20:32 UTC
