### ISSUE TITLE
app start reloading when changing the language

### ISSUE THREAD

**Issue by seifkh97** [aissat/easy_localization#385] opened 2021-05-16 18:44 UTC
hi, I'm new to Flutter and I'm really enjoying it, I started using easy_localization (3.0.0) and everything was good, when I try to change the app language from the setting page,  the app translates the content and stays on the same page but yesterday the app started reloading and back to homescreen which will ruin the app user experience
this is how I change the app locale with dropdown menu:
`onChanged: (newValue) async {
if (newValue == 'English') {
     await context.setLocale(Locale('en'));
} else if (newValue == 'Français') {
     await context.setLocale(Locale('fr'));
 } else if (newValue == 'العربية') {
     await context.setLocale(Locale('ar'));
 }
},`
Flutter: 2.0.3
Thank you

**Comment by Overman775** [comment] 2021-07-15 15:06
@seifkh97 Need example of code to reproduce this bug

**Comment by bw-flagship** [comment] 2023-05-14 10:53
@seifkh97 Closing for now because we can't reproduce without code. if the issue persists, please comment the code here

**Closed as completed by bw-flagship** 2023-05-14 10:53 UTC
