### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by divineaseaku** [aissat/easy_localization#533] opened 2022-11-08 19:23 UTC
Setup easy_localization: 3.0.1 as in example on package but got error **Null check operator used on a null value**  upon running the app. 

My IDE points the error to line 48 `EasyLocalization.of(this)!.delegates;` on on file `easy_localization/src/public_ext.dart`.

**Comment by alireza-rajaei** [comment] 2022-11-15 12:39
i have the same issue inside testWidgets

              debugShowCheckedModeBanner: false,
              localizationsDelegates: context.localizationDelegates,
              supportedLocales: context.supportedLocales,
             

The following _CastError was thrown building Builder(dirty):
Null check operator used on a null value

**Comment by khayargoli** [comment] 2022-11-23 12:48
Same with  me

**Comment by Syed95github** [comment] 2022-12-16 15:15
localizationsDelegates: context.localizationDelegates,
this is causing the error.
Any one solved this ?

**Comment by DirtyNative** [comment] 2022-12-18 13:04
Same problem here. Did anyone find a solution?

**Comment by Mar1anne** [comment] 2023-01-13 09:34
Same here. Any updates?

**Comment by mohkoma** [comment] 2023-02-01 07:08
This is mostly because the parent widget still not fully initialized, Which means the context still doesn't have `localizationDelegates` or `supportedLocales`.
The easy way to solve this is to wrap your `MaterialApp`, `CupertinoApp` or `WidgetsApp` inside a builder.
Something like this:

```
EasyLocalization(
      supportedLocales: [Locale('en', 'US'), Locale('de', 'DE')],
      path: 'assets/translations',
      fallbackLocale: Locale('en', 'US'),
      child: builder(
          builder: (context) {
               return MaterialApp(
                  localizationsDelegates: context.localizationDelegates,
                  supportedLocales: context.supportedLocales,
                  locale: context.locale,
                  home: MyHomePage()
               )
          }
      )
 ),
```

**Comment by Mar1anne** [comment] 2023-02-06 08:55
@mohkoma I had the same implementation as you mentioned.

If I have the following setup: 
Project A -> app with easy localization
Project B -> app with a dependency of Project A. 
I always get the same error in Project B.

**Comment by mohkoma** [comment] 2023-02-06 09:57
@Mar1anne It's hard for me to find the issue without seeing the code, but I assume that the Project B still doesn't have the context that has a loaded easy localisation. Therefore, try to wrap the Project B inside another builder also?

**Comment by Mar1anne** [comment] 2023-02-16 18:16
@mohkoma Maybe, I guess that should work. I changed my implementation since then, but I'll test this out as soon as I got the time. Thanks!

**Comment by bw-flagship** [comment] 2023-05-13 06:08
Several people seem to have this issue, could someone post a sample to reproduce?  I don't think we have a bug here,  but maybe something the docs should cover.

**Comment by SwiftSpotter** [comment] 2023-07-08 23:31
@mohkoma ur solution fixed it for me thanks.

**Comment by bw-flagship** [comment] 2023-07-11 07:12
Closing since the solution seems to work. Thanks @mohkoma

**Closed as completed by bw-flagship** 2023-07-11 07:12 UTC
Labels: waiting for customer response
