### ISSUE TITLE
Not reflected immediately if i change lang

### ISSUE THREAD

**Issue by MuthuHere** [aissat/easy_localization#446] opened 2022-01-13 07:26 UTC
Hi i'm using easy_localization inmy application,

on tap of the change lang button the logs shows like below,

![image](https://user-images.githubusercontent.com/18752533/149284390-9584ed9c-3a49-4780-9028-2d1ab300e3cc.png)

but the text  lang remains same, no change. if restart the app then only it used to change.

![image](https://user-images.githubusercontent.com/18752533/149284577-5f18cf70-ca67-491f-a7bd-d9f3414054b8.png)

**Comment by aymaalo** [comment] 2022-01-13 23:06
I have the same issue here

**Comment by F-anleo** [comment] 2022-01-17 11:04
did you add delegates to your MaterialApp?

**Comment by MuthuHere** [comment] 2022-01-18 07:19
@F-anleo  yes, i did add.

![image](https://user-images.githubusercontent.com/18752533/149889204-40c0a9bc-f22d-4453-a2ac-0f5360092c01.png)

**Comment by singhtaranjeet** [comment] 2022-01-20 14:44
Possible duplicate of https://github.com/aissat/easy_localization/issues/370

**Comment by aissat** [comment] 2022-03-01 23:50
Duplicate of #370

**Closed as completed by aissat** 2022-03-01 23:50 UTC
Labels: duplicate
