### ISSUE TITLE
Not supporting flutter 3

### ISSUE THREAD

**Issue by Kamihimmel** [aissat/easy_localization#483] opened 2022-05-13 08:36 UTC
When upgraded to flutter 3 and run pub get, the package revert to ver 1.2. Tried a lot of things and did not work properly ,the package cant resolve it and cause conflict.Downgrade to 2.10.5 the problem is resolved.

**Comment by aissat** [comment] 2022-05-13 15:27
Duplicate of https://github.com/aissat/easy_localization/pull/470#issuecomment-1124908532

**Closed as completed by aissat** 2022-05-13 15:27 UTC
