### ISSUE TITLE
[🌎 Easy Localization] [WARNING] Localization key [key] not found

### ISSUE THREAD

**Issue by helloalbin** [aissat/easy_localization#394] opened 2021-06-28 07:06 UTC
easy_localization: ^3.0.0

I have migrated my application to NullSafety and I have upgraded to the latest version of easy_localization. After the migration I am getting the following error in my console and the application is not displaying the values for my keys anymore. For every key in my json file I am getting the following error

[🌎 Easy Localization] [WARNING] Localization key [key] not found

Please note that this was working fine before the migration when I was using version 2.3.2.

My code is give below.

```

import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await EasyLocalization.ensureInitialized();

  final _navigatorKey = GlobalKey<NavigatorState>();

  runApp(EasyLocalization(
    supportedLocales: [
      const Locale.fromSubtags(languageCode: "en"),
      const Locale.fromSubtags(languageCode: "fr"),
      const Locale.fromSubtags(languageCode: 'de'), 
    ],
    path: 'assets/lang',
    fallbackLocale: Locale.fromSubtags(languageCode: 'en'),
    startLocale: Locale.fromSubtags(languageCode: 'en'),
    child: MultiProvider(
      providers: [],
      child: MaterialApp(
        navigatorKey: _navigatorKey,
        //   home: SplashScreen(),
      ),
    ),
  ));
}
```

Startup log statements.
[🌎 Easy Localization] [DEBUG] Localization initialized
[🌎 Easy Localization] [DEBUG] Start
[🌎 Easy Localization] [DEBUG] Init state
[🌎 Easy Localization] [INFO] Start locale loaded en
[🌎 Easy Localization] [DEBUG] Build
[🌎 Easy Localization] [DEBUG] Init Localization Delegate
[🌎 Easy Localization] [DEBUG] Init provider
[🌎 Easy Localization] [WARNING] Localization key [select_your_language] not found
[🌎 Easy Localization] [WARNING] Localization key [next_step] not found

**Comment by CaptainDario** [comment] 2021-06-28 11:29
I am getting the same error. However not for all of my translations only for a few of them.

**Comment by emrebayrakdar** [comment] 2021-06-28 11:40
I am getting the same error. Doesn't work at all.

**Comment by emrebayrakdar** [comment] 2021-06-28 12:06
It's working

`Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await EasyLocalization.ensureInitialized();
  await setUpDI();
  runApp(EasyLocalization(supportedLocales: [Locale('en', 'US')], path: AppConstants.LANG_ASSET_PATH, fallbackLocale: Locale('en', 'US'), child: MyApp()));
}

class MyApp extends StatefulWidget {
  const MyApp({key}) : super(key: key);

  @override
  State createState() => MyAppState();
}

class MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return StreamProvider<UserModel>(
      initialData: UserModel.initial(),
      create: (context) => locator<AuthenticationService>().userController.stream,
      child: MaterialApp(
        // localizationsDelegates: [
        //   GlobalMaterialLocalizations.delegate,
        //   GlobalWidgetsLocalizations.delegate,
        //   CountryLocalizations.delegate,
        // ],

        //Easy_localization:
        localizationsDelegates: context.localizationDelegates,
        supportedLocales: context.supportedLocales,
        locale: context.locale,
        debugShowCheckedModeBanner: false,
        title: 'Flutter Demo',
        theme: ThemeData(),
        initialRoute: NavigationConstants.WELCOME,
        onGenerateRoute: AppRouter.generateRoute,
      ),
    );
  }
}`

**Comment by CaptainDario** [comment] 2021-06-29 13:35
For me the problem actually was that I was trying to access the localization before it was initialized.
It has to be run after 
``` dart
runApp(
    EasyLocalization(
        
        ...
        Use localization here
        ...
    )
)
```

**Comment by thedavidpeto** [comment] 2021-07-02 12:30
I'm still experiencing the same issue, could you please provide a full code solution?

**Comment by helloalbin** [comment] 2021-07-03 06:22
@petodavid  Please check the following repo for the full code.

https://github.com/helloalbin/flutter_app/tree/easy_localization

**Comment by sszajbely** [comment] 2021-07-06 13:37
I had the same issue, it seems like the `EasyLocalization.ensureInitialized()` does not wait for all initialization to complete (I await it and it does not work).
My workaround solution to wait for 1 second (with `Future.delayed().then`) before using the EasyLocalization plugin, this time allows the files to be initialized too.

**Comment by CaptainDario** [comment] 2021-07-06 14:24
@machiato32 Yes, that is what i figured out too.
I moved my code which depends on the localization to a later point in my execution orde and now it is working for me.

**Comment by sszajbely** [comment] 2021-07-06 16:53
But this is definitely a bug, which needs to be fixed.

**Comment by MattyBoy4444** [comment] 2021-07-09 15:30
Same problem.  await ensureInitialized is the first line in main.

**Comment by alibt** [comment] 2021-07-12 05:45
I get the same error too.
i'm using   easy_localization: ^3.0.0
this is my main function:
`void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await EasyLocalization.ensureInitialized();
  runApp(
    EasyLocalization(
        supportedLocales: [Locale('fa', 'IR')],
        path: 'assets/translation',
        fallbackLocale: Locale('fa', 'IR'),
        startLocale: Locale('fa', 'IR'),
        child: MultiProvider(
          child: MyApp(),
          providers: providers,
        )),
  );
}`

here is the output of flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-IR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.58.0)
[✓] Connected device (1 available)


• No issues found!

**Comment by alibt** [comment] 2021-07-19 12:19
solved it by adding "await" before EasyLocalizationController.initEasyLocation(); on easy_localization_app.dart line 106. i'll request the merge.

**Comment by mateusz-pietras** [comment] 2021-07-21 16:10
> solved it by adding "await" before EasyLocalizationController.initEasyLocation(); on easy_localization_app.dart line 106. i'll request the merge.

Does not work for me. How awaiting a function that returns a Future would help in awaiting it? You still have to await that future so its still that same future.

**Comment by johnnydevvcodes** [comment] 2021-07-23 05:06
I solved it by  adding the localization attributes in the MaterialApp() as stated in the readme on pub dev.  


```


import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:easy_localization/easy_localization.dart';

void main() async {
WidgetsFlutterBinding.ensureInitialized();
  await EasyLocalization.ensureInitialized();
  
  runApp(
    EasyLocalization(
      supportedLocales: [Locale('en', 'US'), Locale('de', 'DE')],
      path: 'assets/translations', // <-- change the path of the translation files 
      fallbackLocale: Locale('en', 'US'),
      child: MyApp()
    ),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: context.localizationDelegates,
      supportedLocales: context.supportedLocales,
      locale: context.locale,
      home: MyHomePage()
    );
  }
}
```

**Comment by Silv4n** [comment] 2021-08-29 11:52
I have the same issue, unfortunatly none of the above proposed changes worked out for me.

**Comment by CripyIce** [comment] 2021-09-01 13:13
Same here.. None of the above proposed changes worked out for me.

**Comment by FatiMooni** [comment] 2021-09-13 11:12
The same issue, none of the above-suggested answers worked!

**Comment by sarimk80** [comment] 2021-10-15 11:38
If anyone still having this issue for **csv files**  remove the easy_localization_loader. from pubspec and create a new file 
```
import 'dart:developer';

import 'package:csv/csv.dart';
import 'package:csv/csv_settings_autodetection.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;


class CsvAssetLoader extends AssetLoader {
  CSVParser? csvParser;

  @override
  Future<Map<String, dynamic>> load(String path, Locale locale) async {
    if (csvParser == null) {
      log('easy localization loader: load csv file $path');
      csvParser = CSVParser(await rootBundle.loadString(path));
    } else {
      log('easy localization loader: CSV parser already loaded, read cache');
    }
    return csvParser!.getLanguageMap(locale.toString());
  }
}

class CSVParser {
  final String fieldDelimiter;
  final String strings;
  final List<List<dynamic>> lines;

  static final csvSettingsDetector =
      FirstOccurrenceSettingsDetector(eols: ['\r\n', '\n']);

  CSVParser(this.strings, {this.fieldDelimiter = ','})
      : lines = CsvToListConverter(csvSettingsDetector: csvSettingsDetector)
            .convert(strings, fieldDelimiter: fieldDelimiter);

  List getLanguages() {
    return lines.first.sublist(1, lines.first.length);
  }

  Map<String, dynamic> getLanguageMap(String localeName) {
    final indexLocale = lines.first.indexOf(localeName);

    var translations = <String, dynamic>{};
    for (var i = 1; i < lines.length; i++) {
      translations.addAll({lines[i][0]: lines[i][indexLocale]});
    }
    return translations;
  }
}

```

**Comment by YouSour** [comment] 2021-11-24 06:56
got the same problem , need help 😞

**Comment by abdalazeez1** [comment] 2022-06-30 16:44
same issue any solution ??

**Comment by abdalazeez1** [comment] 2022-06-30 16:56
i solved problem by delete all file generated and execute 
flutter pub run easy_localization:generate --source-dir ./translations         

flutter pub run easy_localization:generate
 flutter pub run easy_localization:generate --source-dir 'translations' --output-dir 'lib/generated' --output-file 'translations.g.dart' --format keys

**Comment by Caffo17** [comment] 2022-07-06 14:37
I solved wrapping the MaterialApp's `home` with a `Builder`
```Dart
return MaterialApp(
      localizationsDelegates: context.localizationDelegates,
      supportedLocales: context.supportedLocales,
      locale: context.locale,
      home: Builder(
        builder: (context) {
          return MyWidget();
        },
      ),
);        
```

I think the problem is related to the BuildContext passed in the `build` method that hasn't registered yet the localization delegates of the MaterialApp. In this way the Builder use a context child of the MaterialApp

**Comment by 100bhyun** [comment] 2022-11-21 18:03
holy moly.. I solved it by adding '/' at the end of assets/translations...

**Comment by Turbozanik** [comment] 2022-12-21 09:40
Same issue here, 2/3 of my json file is loaded just fine, and 1/3 is not found all the time.
I have used all suggested solutions above, but non of them helped.
lib version 3.0.1.

My json is looking like this:
![image](https://user-images.githubusercontent.com/7550948/208873165-dcd60d99-8c0a-47db-92e5-7f33dfbc732f.png)
And everything under points array is not loaded:
![image](https://user-images.githubusercontent.com/7550948/208873268-6b0422b9-9dbf-4e2f-adb6-8152dfba33b1.png)

**Comment by buraktahap** [comment] 2023-01-05 14:00
I am still having this issue. Did anybody found a solution?

**Comment by Alex11144** [comment] 2023-02-28 15:43
I have added this line into EasyLocalization(after runApp) and everything worked : 
   startLocale: Locale.fromSubtags(languageCode: 'en'),

**Comment by Linloir** [comment] 2023-04-13 06:21
Hi there,
I worked out with this issue by **always using translation in the state of stateful widgets**.
---
I guess that there are jobs to be done after the application has started, and by pass the delegates by context to the root `MaterialApp`, the changes happened in the delegates triggers rebuilds of the widgets, thus giving them correct translations afterwards.

Here is an example of **NOT** using the translation in the `State`:
```dart
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await EasyLocalization.ensureInitialized();

  runApp(
    EasyLocalization(
      supportedLocales: const [
        Locale('zh', 'CN'),
        Locale('en', 'US'),
      ],
      path: 'assets/translations',
      fallbackLocale: const Locale('en', 'US'),
      useOnlyLangCode: false,
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      localizationsDelegates: context.localizationDelegates,
      supportedLocales: context.supportedLocales,
      locale: context.locale,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  // ↓↓↓↓↓↓↓↓↓↓↓↓↓ misuse of translations ↓↓↓↓↓↓↓↓↓↓↓↓↓
  final String title = 'title'.tr(args: ['Flutter']);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

While the one with title put in the `build` method working fine:
```dart
class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  // final String title = 'title'.tr(args: ['Flutter']);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
          // ↓↓↓↓↓↓↓↓↓↓↓↓↓ correct use of translations ↓↓↓↓↓↓↓↓↓↓↓↓↓
        title: Text('title'.tr(args: ['Flutter'])),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

**Comment by bw-flagship** [comment] 2023-05-16 07:31
I think a lot of very different problems are merged in this issue. A lot of them will be solved by the solutions of @Caffo17 and @johnsargado. However, if someone still has this problem, please comment here and code, so maintainers can reproduce it.

**Comment by ObidjonJoraboyev** [comment] 2024-05-05 16:54
> I solved it by adding the localization attributes in the MaterialApp() as stated in the readme on pub dev.
> 
> ```
> 
> 
> import 'package:flutter/material.dart';
> import 'package:flutter_localizations/flutter_localizations.dart';
> import 'package:easy_localization/easy_localization.dart';
> 
> void main() async {
> WidgetsFlutterBinding.ensureInitialized();
>   await EasyLocalization.ensureInitialized();
>   
>   runApp(
>     EasyLocalization(
>       supportedLocales: [Locale('en', 'US'), Locale('de', 'DE')],
>       path: 'assets/translations', // <-- change the path of the translation files 
>       fallbackLocale: Locale('en', 'US'),
>       child: MyApp()
>     ),
>   );
> }
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       localizationsDelegates: context.localizationDelegates,
>       supportedLocales: context.supportedLocales,
>       locale: context.locale,
>       home: MyHomePage()
>     );
>   }
> }
> ```

thank you bro ,me too

**Closed as completed** 2024-05-05 17:25 UTC
Labels: duplicate, waiting for customer response

**Comment by officialismailshah** [comment] 2024-07-03 09:39
> ```
>  I have added this line into EasyLocalization(after runApp) and everything worked : 
> ```
> 
> startLocale: Locale.fromSubtags(languageCode: 'en'),

this worked for me but none of the above

**Comment by chitgoks** [comment] 2025-01-07 10:46
> I had the same issue, it seems like the `EasyLocalization.ensureInitialized()` does not wait for all initialization to complete (I await it and it does not work). My workaround solution to wait for 1 second (with `Future.delayed().then`) before using the EasyLocalization plugin, this time allows the files to be initialized too.

the delay worked for me.
