### ISSUE TITLE
can't generate a loder file by cmd

### ISSUE THREAD

**Issue by sarfas-texol** [aissat/easy_localization#508] opened 2022-07-26 06:58 UTC

**Comment by sarfas-texol** [comment] 2022-07-26 06:59
package version 3.0.1

**Comment by FabiKel** [comment] 2022-08-23 12:15
Propably the same issue: https://github.com/aissat/easy_localization/issues/492
No solution yet :(

**Comment by bw-flagship** [comment] 2023-05-14 12:41
closing because duplicate of #492

**Closed as completed by bw-flagship** 2023-05-14 12:41 UTC
