### ISSUE TITLE
plural and arguments don't work in nested keys

### ISSUE THREAD

**Issue by sasarivera** [aissat/easy_localization#401] opened 2021-07-07 17:52 UTC
Hi,

This doesn't work:

```
{
    "category": {
         "result": {
             "zero": "You not have money",
             "one": "You have {} dollar",
             "many": "You have {} dollars",
             "other": "You have {} dollars"
         },
         "total": "{} items"
    }
}

Text('category_result').plural(Count)
Text('cateory_total').tr(args: [total]);
```

but if I remove the nested keys it works

```
{
         "result": {
             "zero": "You not have money",
             "one": "You have {} dollar",
             "many": "You have {} dollars",
             "other": "You have {} dollars"
         },
         "total": "{} items"
}

Text('result').plural(Count)
Text('total').tr(args: [total]);
```

I'm using the 2 commands to generate the keys:

```
flutter pub run easy_localization:generate -S "assets/translations" -O "lib/translations"
flutter pub run easy_localization:generate -S "assets/translations" -O "lib/translations" -o "locale.keys.g.dart" -f keys
```

and I can see the keys being generated

```
abstract class  LocaleKeys {
  static const category_result = 'category.result';
  static const category.total = 'category_total';
}
```

in the UI appears as
category_result.many (not the translation)

Thanks for any help you can provide

**Comment by Overman775** [comment] 2021-07-26 11:04
update package and rerun your generator, i have difrent keys in my output 
```
abstract class  LocaleKeys {
  static const category_result = 'category.result';
  static const category_total = 'category.total';
  static const category = 'category';
}
```

then you need get translation like this:
Text(LocaleKeys.category_result.plural(Count))
Text(LocaleKeys.category_total).tr(args: [total]);

**Comment by sasarivera** [comment] 2021-07-28 19:59
I have the latest package. I still have problems with using plural for nested keys. The workaround is just add those key to the root

**Comment by bw-flagship** [comment] 2023-05-14 10:56
Closing since we could not reproduce with the given code. @sasarivera please comment if the issue persists

**Closed as completed by bw-flagship** 2023-05-14 10:56 UTC

**Comment by whipsterCZ** [comment] 2025-03-03 15:47
I have same problem

my keys look like this
```
"storage.folder.items.text": {
    "one": "Item",
    "other": "Items",
     "zero": "Items"
  },
```

if i use plain key 
`storage.folder.items.text.other":"Items"` then it works...
