### ISSUE TITLE
[WARNING] Don't import implementation files from another package on `package:easy_localization/src/public_ext.dart` import

### ISSUE THREAD

**Issue by koddr** [aissat/easy_localization#436] opened 2021-11-23 04:34 UTC
Hi,

After installing your package (`v3.0.0`), VS Code always shows me this warning message:

![Screenshot 2021-11-23 at 07 27 26](https://user-images.githubusercontent.com/11155743/142971508-dfd4b3da-4d16-4894-bc0e-e93f6f996561.png)

But I've not imports in other files with `package:easy_localization/src/public_ext.dart`, only in this…

And on VS Code suggestion:

![Screenshot 2021-11-23 at 07 55 49](https://user-images.githubusercontent.com/11155743/142973424-5a77e838-a89f-4db0-bf06-a8fbe3116436.png)

How to solve this? Please.

**Comment by akiller** [comment] 2021-11-25 13:48
For me ```import 'package:easy_localization/easy_localization.dart';``` seems to work without the error.

I'm using Android Studio (I love vscode too!) and it also sometimes gets confused with importing files from the wrong place as well, and not just with this library.

**Comment by mdeandrea-mrmilu** [comment] 2022-05-10 12:05
If use `import 'package:easy_localization/easy_localization.dart';` the issue is resolved?
If yes, please close this issue

**Comment by bw-flagship** [comment] 2023-05-10 06:23
Closed since most likely resolved

**Closed as completed by bw-flagship** 2023-05-10 06:23 UTC
