### ISSUE TITLE
set locale behavior not working properly

### ISSUE THREAD

**Issue by Ahmed-Fathy-dev** [aissat/easy_localization#502] opened 2022-06-28 10:48 UTC
I had a problem when I changed the language using context.setLocale(). 
Some words are translated and others only change the direction and the words are only translated when I do Hot Reload or Hot Restart

![tr_issue](https://user-images.githubusercontent.com/46655611/176160862-9b609c41-f556-4593-9e4a-ed770d89adf6.PNG)

![tr_issue2](https://user-images.githubusercontent.com/46655611/176164952-7224753b-13a7-4c21-ad1a-ca4c321b37f2.PNG)

**Comment by EhabSalah** [comment] 2022-07-04 13:40
Same is happening with me as well, `setLocale` randomly sometimes only changes layout direction with the same translations.

**Comment by AliHoseinpoor** [comment] 2022-10-18 11:17
i have the same problem

**Comment by ChangJoo-Park** [comment] 2022-11-08 09:10
+1

**Comment by Jasco07122021** [comment] 2022-11-30 12:40
+1

**Comment by aissat** [comment] 2023-02-24 13:49
Duplicate of #552

**Closed as completed by aissat** 2023-02-24 13:49 UTC
