### ISSUE TITLE
The language doesn't change in the application unless I make a hot restart.

### ISSUE THREAD

**Issue by mohamedmohamedy** [aissat/easy_localization#640] opened 2023-12-31 11:41 UTC
The texts don't change unless I make a hot restart, even though the directions of the texts change according to the new language and the console logs reassures that the locale had changed.
Using Version 3.0.3

**Video for the problem**

https://github.com/aissat/easy_localization/assets/80913778/e77d23b6-24aa-459a-a307-e6dec29ae94f

### **Localization class file**
```import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';

class AppLocal {
  static String path = 'assets/locale';
  static const List<Locale> supportLocals = [
    Locale('en'),
    Locale('ar'),
  ];

  static bool? isEnglish;

  ///switch locals
  static Future<void> toggleBetweenLocales(BuildContext context) async {
    if (isEnglish!) {
      await context.setLocale(supportLocals[0]);
    } else {
      await context.setLocale(supportLocals[1]);
    }
  }

  ///reset device local
  static Locale? fallbackLocal(
    Locale? currentLocal,
    Iterable<Locale> supportLocal,
  ) {
    if (currentLocal != null) {
      for (final Locale locale in supportLocal) {
        if (locale.languageCode == currentLocal.languageCode) {
          return currentLocal;
        }
      }
    }
    return null;
  }
}
```
### **Language switch file**
```import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';

import '../../../../../core/resources/localizations.dart';
import '../../../../../core/resources/values_manager.dart';
import '../../../../../core/resources/strings_manager.dart';

class LanguageSwitch extends StatefulWidget {
  const LanguageSwitch({super.key});

  @override
  State<LanguageSwitch> createState() => _LanguageStateSwitch();
}

class _LanguageStateSwitch extends State<LanguageSwitch> {
  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    if (context.locale.languageCode == UnTranslatedStrings.en) {
      AppLocal.isEnglish = true;
    } else {
      AppLocal.isEnglish = false;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Flexible(
          fit: FlexFit.tight,
          child: ListTile(
            tileColor: Colors.transparent,
            contentPadding: const EdgeInsets.all(DoubleManager.d_0),
            title: const Text(UnTranslatedStrings.english),
            leading: Radio<bool>(
              value: true,
              groupValue: AppLocal.isEnglish,
              onChanged: (bool? value) async {
                AppLocal.isEnglish = value!;
                await AppLocal.toggleBetweenLocales(context);
                setState(() {});
              },
            ),
          ),
        ),
        Flexible(
          child: ListTile(
            tileColor: Colors.transparent,
            title: const Text(UnTranslatedStrings.arabic),
            leading: Radio<bool>(
              value: false,
              groupValue: AppLocal.isEnglish,
              onChanged: (bool? value) async {
                AppLocal.isEnglish = value!;
                await AppLocal.toggleBetweenLocales(context);
                setState(() {});
              },
            ),
          ),
        ),
      ],
    );
  }
}
```
### Main file
```import 'package:easy_localization/easy_localization.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter/material.dart';
import 'package:sizer/sizer.dart';

import 'firebase_options.dart';
import 'core/resources/routes.dart';
import 'core/utils/splash_screen.dart';
import 'core/global/bloc_observer.dart';
import 'core/resources/theme_manager.dart';
import 'core/global/state_management.dart';
import 'core/resources/localizations.dart';
import 'core/resources/strings_manager.dart';
import 'core/global/dependencies_container.dart' as di;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await EasyLocalization.ensureInitialized();
  await di.init();
  Bloc.observer = MyBlocObserver();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return EasyLocalization(
      supportedLocales: AppLocal.supportLocals,
      path: AppLocal.path,
      child: MultiBlocProvider(
        providers: StateManagement.providers,
        child: Sizer(
          builder: (context, orientation, deviceType) => MaterialApp(
            debugShowCheckedModeBanner: false,
            title: UnTranslatedStrings.appName,
            theme: AppTheme.getApplicationLightTheme(),
            home: const SplashScreen(),
            routes: Routes.routes,
            localizationsDelegates: context.localizationDelegates,
            supportedLocales: context.supportedLocales,
            locale: context.locale,
          ),
        ),
      ),
    );
  }
}
```

**Comment by SnirYaZem** [comment] 2024-01-18 14:40
I'm also having the same problem. I managed to solve it by getting the strings ('...'.tr()) from a non static source.

from:
`class AppStrings {
  static String homePageTitle = 'title'.tr();
}`

to:
`class AppStrings {
  String homePageTitle = 'title'.tr();
}`

**Comment by mohamedmohamedy** [comment] 2024-01-22 11:52
> I'm also having the same problem. I managed to solve it by getting the strings ('...'.tr()) from a non static source.
> 
> from: `class AppStrings { static String homePageTitle = 'title'.tr(); }`
> 
> to: `class AppStrings { String homePageTitle = 'title'.tr(); }`

I don't think it's a good practice, as it will make a new instance of the AppStrings class every time you call a string from it.

**Comment by mohamedmohamedy** [comment] 2024-01-22 11:59
The solution I found to solve this error was by getting the tr() call outside the StringsManager class, and call it after the calling of the string itself like that (StringsManager.test.tr()) and it worked fine. 

I think the problem was that the StringsManager class make only one instance at the beginning of the application, and it doesn't make a new one after the language changes, so the values inside it remains the same.

**Comment by ihou** [comment] 2024-01-25 07:17
Use this Code,ChatGpt give me this solution,it works!!!

1. wrap your root widget with RestartWidget
2. call RestartWidget.restartApp



class RestartWidget extends StatefulWidget {
  final Widget child;

  RestartWidget({Key? key, required this.child}) : super(key: key);

  static restartApp(BuildContext context) {
    context.findAncestorStateOfType<_RestartWidgetState>()?.restartApp();
  }

  @override
  _RestartWidgetState createState() => _RestartWidgetState();
}

class _RestartWidgetState extends State<RestartWidget> {
  Key key = UniqueKey();

  void restartApp() {
    setState(() {
      key = UniqueKey();
    });
  }

  @override
  Widget build(BuildContext context) {
    return KeyedSubtree(
      key: key,
      child: widget.child,
    );
  }
}

**Comment by ihou** [comment] 2024-01-25 07:19
Use this Code,ChatGPT gives me this solution,it works!!!

1. wrap your root widget with RestartWidget
2. call RestartWidget.restartApp

```
import 'package:flutter/material.dart';

class RestartWidget extends StatefulWidget {
  final Widget child;

  const RestartWidget({Key? key, required this.child}) : super(key: key);

  static restartApp(BuildContext context) {
    context.findAncestorStateOfType<_RestartWidgetState>()?.restartApp();
  }

  @override
  State createState() => _RestartWidgetState();
}

class _RestartWidgetState extends State<RestartWidget> {
  Key key = UniqueKey();

  void restartApp() {
    setState(() {
      key = UniqueKey();
    });
  }

  @override
  Widget build(BuildContext context) {
    return KeyedSubtree(
      key: key,
      child: widget.child,
    );
  }
}

```

**Comment by aissat** [comment] 2024-01-27 22:52
@mohamedmohamedy Duplicate of https://github.com/aissat/easy_localization/issues/590

https://github.com/aissat/easy_localization/issues/552#issuecomment-1443720728

**Closed as completed** 2024-02-03 20:14 UTC
